// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtlzdfgatfxysblkhxzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bHpkZmdhdGZ4eXNibGtoeHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTI4MzgsImV4cCI6MjA2NjY4ODgzOH0.2HA02Fe9Hyf4GRoqSbmuAQQVUjB5II9aslbfJ296qzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);